valohai/valohai-utils

- tests/test_logs.py
- valohai/metadata.py
Starting flushes with a newline, we ensure the JSON gets printed on it's own line and Valohai recognizes it.
> Flush with a newline, printing JSON on own line

- mypy.ini
- setup.py
- tests/test_pipeline.py
- tests/test_pipeline_yaml/test1.expected.valohai.yaml
- tests/test_pipeline_yaml/test1.original.valohai.yaml
- tests/test_pipeline_yaml/test1.py
- tests/utils.py
- valohai/__init__.py
- valohai/internals/pipeline.py
Integrating `valohai-papi` into `valohai-utils`.
Technically we could integrate `valohai-papi` directly into `valohai-cli`, but I feel like all the Python to YAML shenanigans should live in the `valohai-utils`. As a bonus, the user now needs to import from one place only (`import valohai`).
The integration happens through single method `get_pipeline_from_source()` and the rest of the PR is testing.
> Add support for defining pipelines via papi integration (fixes #26)

- setup.py
- valohai/internals/parsing.py
If valohai-utils faces code like...
```
X['Intercept'] = 1.
```
...it can't eval (which is expected). However, it is currently only designed to pass on `ValueError`, but fails on the `AttributeError` that evaling this code raises.
> Expect AttributeError when trying to eval assignments (fixes #43)

- tests/test_yaml/test1.expected.valohai.yaml
- tests/test_yaml/test1.py
- valohai/internals/yaml.py
Users want to define optional inputs with `valohai-utils`, but currently, it is not supported.
You define an input with `valohai-utils` like this:
```
default_inputs = {
"my_input": "https://herpderp.com/lol.txt"
}
```
Generated YAML:
```
- name: my_input
default:
- https://herpderp.com/lol.txt
optional: false
```
This PR introduces support for optional inputs. Just leave the value empty:
```
default_inputs = {
"my_input": ""
}
```
Generated YAML:
```
- name: my_input
optional: true
```
> Make inputs optional if the defaults are set empty

- tests/test_inputs.py
- tests/valohai_test_environment.py
- valohai/internals/vfs.py
> Don't mangle filenames when extracted from containers

- tests/test_parsing.py
- tests/test_yaml.py
- tests/test_yaml/test6.expected.valohai.yaml
- tests/test_yaml/test6.ipynb
- tests/test_yaml/test7.expected.valohai.yaml
- tests/test_yaml/test7.ipynb
- tests/utils.py
- valohai/internals/notebooks.py
- valohai/internals/yaml.py
This PR adds notebook source file support for the YAML generator that the Valohai CLI is calling.
You can create YAML step from Python file today:
```
vh yaml step hello.py
```
Now with valohai-utils support for notebooks, you can do the same with notebooks:
```
vh yaml step hello.ipynb
```
This will generate the YAML step that runs a notebook using Papermill. The notebook is assumed to use valohai-utils to define parameters and inputs.
Note: This PR has some copy-pasta code from Jupyhai, related to parsing source code from notebooks. We don't want valohai-utils to be dependent on Jupyhai, but Jupyhai is already dependent on valohai-utils. Once this PR is merged in, we should DRY at the Jupyhai side if possible.
> Support notebooks in YAML generator (fixes #61)

- tests/test_inputs.py
- tests/valohai_test_environment.py
- valohai/inputs.py
- valohai/internals/vfs.py
**What**
For a single Valohai input, we have `.path()` `.paths()` `.stream()` `.streams()`.
This PR introduces a new parameter `filter_path`, which allows filtering a subset of all the files of the input, based on their file path. Wildcards are supported for both single and double notation.
Example: `valohai.inputs("myinput").paths("folder/**/foo/*.jpg")`
**Why**
If your input has multiple files, but you just want one (or subset).
Before this PR:
```
import fnmatch
for path in fnmatch.filter(valohai.inputs("myinput").paths(), "weights.pb"):
print(path)
```
After this PR:
```
path = valohai.inputs("myinput").path("weights.pb"):
```
Also supports stuff like:
```
for image_path in valohai.inputs("myinput").paths("folder/**/foo/*.jpg"):
print(image_path)
```
> Add wildcard support for paths() and streams() (fixes #54)

- tests/test_download.py
- tests/test_parsing/test1.inputs.json
- tests/test_parsing/test3.inputs.json
- tests/test_yaml/test1.expected.valohai.yaml
- tests/test_yaml/test2.expected.valohai.yaml
- tests/test_yaml/test3.expected.valohai.yaml
- tests/test_yaml/test4.expected.valohai.yaml
- tests/test_yaml/test7.expected.valohai.yaml
- tests/test_yaml/test8.expected.valohai.yaml
- tests/test_yaml/test8.original.valohai.yaml
- tests/test_yaml/test8.py
- valohai/internals/parsing.py
- valohai/internals/yaml.py
- valohai/utils.py
Today you can feed your default parameters to `prepare()` like this
```
params = {
"learning-rate": 0.001,
"dropout": 0.2,
}
```
After this PR, the experts have this option, too:
```
params = {
"batch_size": {
"default": 32,
"type": "integer",
"description": "Size of the training batch",
"pass-as": "--batch:{v}",
"optional": True,
"multiple-separator": "!"
}
}
```
Same works for inputs, too!
**Minor additional tweaks**: 
* If you have an input with single default, the parser no longer forces that into an array. This makes the resulting YAML cleaner.
* Changed wikimedia.org URLs to our own S3 URLs for the tests with real downloading
Fixes #56
> Allow full parameter and input definition via valohai-utils prepare()

- tests/conftest.py
- tests/test_compress.py
- valohai/internals/files.py
- valohai/outputs.py
You can now make calls like:
```
valohai.outputs('resized').compress("**/*.png", "images.zip", remove_originals=True)
valohai.outputs('resized').compress("/tmp/foo/**/derp/*.png", "images.zip", remove_originals=True)
```
And get a meaningful folder structure inside the archive:
```
train/hello.png
test/jello.png
```
fixes #58
> Recursively compress output with ** wildcards (fixes #58)

- tests/test_inputs.py
- valohai/inputs.py
Shortcut to get input folder path:
```
valohai.inputs("my_images").dir_path
```
One aesthetical decision here was that we have `valohai.inputs("my_images").path("file.txt")` and it might be considered consistent to have `valohai.inputs("my_images").dir_path()` method instead of property. 
I chose property over method but can be argued either way.
fixes #51
> Add dir_path property to inputs (fixes #51)

- tests/test_prepare.py
- valohai/internals/input_info.py
Wildcards were broken for local paths. List of local paths used to be broken, too.
This code:
```
valohai.prepare(step="train", default_inputs={"myinput": "*.png"})
```
Would try to download the local file path and throw an error. This PR fixes it.
Also lists as default for local inputs:
```
valohai.prepare(step="train", default_inputs={"myinput": ["1.png", "2.png"]})
```
Were fixed in the big refactor earlier, but this PR adds a test for it.
Fixes #76 
Fixes #65
> Fix local inputs with multiple files + add tests

- valohai/internals/input_info.py
Before #83 (valohai-utils 0.1.13) the new field crashes valohai-utils.
Post #83, the new field (added 2022-03-16) is quietly ignored.
This adds proper parsing for it to the Input instance.
> Parse inputs.json datum_id

- valohai/internals/compression.py
- valohai/internals/parsing.py
- valohai/internals/vfs.py
Better to get a real error, not just `raise NotImplementedError(): NotImplementedError`.
> Make NotImplementedErrors more verbose

- .gitignore
- README.md
- setup.cfg
- tests/conftest.py
- tests/test_distributed.py
- tests/test_parsing_distributed/exposed-ports.json
- tests/test_parsing_distributed/is-master.json
- tests/test_parsing_distributed/is-not-master.json
- tests/test_parsing_distributed/malformed.json
- tests/test_parsing_distributed/network-host.json
- tests/test_parsing_distributed/no-public-ips.json
- valohai/__init__.py
- valohai/distributed.py
- valohai/internals/distributed_config/__init__.py
- valohai/internals/distributed_config/distributed_config.py
- valohai/internals/distributed_config/member.py
- valohai/internals/distributed_config/utils.py
- valohai/internals/global_state.py
- valohai/paths.py
Fixes #87 
TODO:
Also includes other small improvements here and there.
> Add `valohai.distributed` with config parsing

- valohai/__init__.py
- valohai/controller_api.py
- valohai/internals/api_calls.py
- valohai/paths.py
This PR adds a helper function `valohai.set_status_detail`.
It requires `requests` to be installed; it's not a dependency at all for `valohai-utils` (and likely will never be).
> Add `valohai.set_status_detail`

- tests/test_outputs.py
- valohai/outputs.py
Pretty much this https://github.com/valohai/valohai-utils/pull/67 except for outputs
Shortcut to get output folder path:
```
valohai.outputs().dir_path
```
> Output path

- README.md
- tests/test_parsing_priorities.py
- tests/test_prepare.py
- tests/test_yaml/test7.expected.valohai.yaml
- tests/test_yaml/test7.ipynb
- tests/valohai_test_environment.py
Wikimedia was complaining about our generic user-agent: https://github.com/valohai/valohai-utils/actions/runs/3351039320/jobs/5552232384
> Replace third-party URLs in tests with ours

- valohai/internals/download.py
We don't actually need `tqdm` as a dependency for `valohai-utils`, it's just for fancy progress bars.
(This PR became simpler now that we're targeting Python 3.7 which has `nullcontext`.)
> Don't hard-require `tqdm` for downloads

- tests/test_pipeline_yaml/test1.expected.valohai.yaml
- tests/test_yaml/test1.expected.valohai.yaml
- tests/test_yaml/test2.expected.valohai.yaml
- tests/test_yaml/test3.expected.valohai.yaml
- tests/test_yaml/test4.expected.valohai.yaml
- tests/test_yaml/test5.expected.valohai.yaml
- tests/test_yaml/test6.expected.valohai.yaml
- tests/test_yaml/test7.expected.valohai.yaml
- tests/test_yaml/test8.expected.valohai.yaml
- tests/utils.py
Valohai-yaml has recently updated its serialisation logic, which breaks valohai-utils test suite due to exact YAML string representation comparisons done here.
Test suite will pass once valohai-yaml PR https://github.com/valohai/valohai-yaml/pull/106 is merged and new release is prepared. 
This should be an exhaustive list of valohai-yaml updates maintained in this PR:
- multiple-separator is not rendered where not applicable https://github.com/valohai/valohai-yaml/pull/106
- Override is rendered differently https://github.com/valohai/valohai-yaml/pull/103
- steps sorting has changed https://github.com/valohai/valohai-yaml/pull/93
In addition, test suite is improved to output diffs of failed YAML tests to make future maintenance more straightforward.
We could consider some kind of …
> Maintain valohai-yaml related tests

- .github/workflows/ci.yml
Analogue of https://github.com/valohai/gitignorant/pull/8
> Configure publishing via CI (using a trusted publisher)

- pyproject.toml
Newer version of `hatch` will require the target to be specify when the our python package name is not the same as its pip package name.
> Specify build target for wheel

- .gitignore
- tests/test_yaml/test1.expected.valohai.yaml
- tests/test_yaml/test1.py
- tests/test_yaml/test2.expected.valohai.yaml
- tests/test_yaml/test2.py
- tests/test_yaml/test3.expected.valohai.yaml
- tests/test_yaml/test3.py
- tests/test_yaml/test4.expected.valohai.yaml
- tests/test_yaml/test4.py
- tests/test_yaml/test7.expected.valohai.yaml
- tests/test_yaml/test8.expected.valohai.yaml
- valohai/internals/utils.py
- valohai/internals/yaml.py
Resolve #49 
When generating/updating config to `valohai.yaml`, we will ignore the value of inputs if it's pointing to a local file path
> Ignore default value for inputs if it's local file path

- tests/test_prepare.py
- valohai/internals/global_state_loader.py
Let `argparser` knows how to properly parse the parameter of type `list` by providing a callback that split the parameter using comma as default.
> Make parsing parameter from CLI work properly when it is a list

- tests/test_webhook.py
- valohai/__init__.py
- valohai/triggers.py
- valohai/webhooks.py
This allows calling web hook triggers on the same project by name, with automatic configuration for authentication.
```
import valohai
valohai.triggers('pipeline for special occasions').post({'hello': 'world'})
```
This requires updates to other Valohai components to put the necessary configuration and interfaces in place to support trigger discovery, which are now generally available.
> Add trigger catalog and integrated web hook support

- requirements-dev.in
- tests/test_download.py
- valohai/internals/download.py
As discussed in the Continental support channel, we need the possibility to download datum:// input files to run an execution locally. This pull request adds this feature to valohai-utils' download.py.
Using this we were able to run a complete execution, locally.
To test, perform the following steps
- log in to valohai with `vh login`
- link a project, if you want to use aliases with `vh link`
- execute python snippet (make sure to replace `my_models_alias` and `01941935-832f-16d4-af69-6a9bf6bf4df6` with existent data)
```python
import valohai
valohai.prepare(
step="predict",
default_inputs={
"model-http": "http://example.com",
"model-alias": "datum://my_models_alias",
"model-id": "datum://01941935-832f-16d4-af69-6a9bf6bf4df6",
},
)
print(valohai.inputs("model-http").path()) …
```
> download datum://id and datum://alias files, run execution locally, using project data files

- README.md
- tests/test_yaml/test1.expected.valohai.yaml
- tests/test_yaml/test3.expected.valohai.yaml
- tests/test_yaml/test4.expected.valohai.yaml
- tests/test_yaml/test4.original.valohai.yaml
- tests/test_yaml/test5.original.valohai.yaml
- valohai/consts.py
Using a more modern Python image by default instead of one way past end of life.
`vh yaml step FILE.PY` uses this image as a default.
There have been some issues e.g. with PyTorch with images newer than 3.11, so we’ll use that as the default for now.
The slim image is much smaller (~87%) than the regular Python image, and should work with most things just fine, so setting that as the default is good for making the executions more nimble.
> Update default Python image

- tests/test_output_properties.py
- valohai/__init__.py
- valohai/output_properties.py
Resolves #138 
Add a helper class that takes care of execution output properties handling:
- file name & location
- JSON lines format
- opening file, writing data, closing file
When creating datasets, a summary is output to the execution log: created dataset versions & how many files were included.
Tests include a metadata handler for 100 000 files, the code scales pretty linearly upwards from that (tested manually with 1 million metadata entries).
This version is a bit more simplified than earlier drafts: adding files to datasets is done separately from adding the other properties; this is to keep the user interface as simple and easy as possible (and it also accommodates the most usual use cases better).
Example usage:
```python
with valohai.output_properties() as properties: …
```
> Output properties helper

- tests/conftest.py
- tests/test_download.py
- valohai/internals/download.py
- valohai/internals/input_info.py
If accessing inputs using `valohai.input('...')` that have not been downloaded, check if we have the necessary input metadata and API endpoint access to get download URLs for those inputs and download them before proceeding.
> Support requesting on-demand inputs when using valohai input utilities

- tests/test_execution_config.py
- valohai/__init__.py
- valohai/execution.py
Resolves #140
Allow fetching basic execution information (such as the ID of the currently running execution) more easily (and without having to know where and how the configuration is stored).
Only return some very basic information for now – more info, and other helpers besides fetching the configuration, may be added later, if/when they are needed.
Documentation to be added in a separate PR.
```python
import valohai
execution_config = valohai.execution().config
print(f"Execution ID: {execution_config.id}")
print(f"Execution title: {execution_config.title}")
print(f"Execution counter: {execution_config.counter}")
```
> Add execution configuration helper

- .github/workflows/ci.yml
The minimum Python version will be raised later, as Python 3.7 is at end of life.
Ref https://github.com/actions/runner-images/issues/10636
> Pin CI test to Ubuntu 22.04, the last version that supports Python 3.7

- README.md
Documents #141
Add an example of using `valohai.execution().config`.
Also contains some formatting fix ups to bring the README up to snuff.
> 📝 Add execution info to README

- .github/workflows/ci.yml
- pyproject.toml
- requirements-dev.in
- tests/utils.py
Python 3.7 has been EOL for 18 months now. Our other software doesn't support it anymore either.
> Drop support for Python 3.7
